# Reference all services likely to be used in the application here
parameters:
    router.config_file: routes
    bindings.config_file: bindings
    connections.config_file: connections
    config.class: \Backend\Core\Utilities\Config

services:
    router.config:
        class: \Backend\Core\Utilities\Config
        factory_class: \Backend\Core\Utilities\Config
        factory_method: getNamed
        arguments:
            - @parser
            - %router.config_file%
    router:
        class: \Backend\Core\Utilities\Router
        arguments:
            - @router.config
            - @callback_factory
    bindings.config:
        class: %config.class%
        factory_class: %config.class%
        factory_method: getNamed
        arguments:
            - @parser
            - %bindings.config_file%
    binding_factory:
        class: \Backend\Base\Utilities\BindingFactory
        arguments:
            - @bindings.config
            - @connections.config
    callback_factory:
        class: \Backend\Core\Utilities\CallbackFactory
    connections.config:
        class: %backend.config.class%
        factory_class: %config.class%
        factory_method: getNamed
        arguments:
            - @parser
            - %connections.config_file%
    parser:
        class: \Symfony\Component\Yaml\Parser
    request:
        class: \Backend\Core\Request
    renderer:
        class: \Backend\Modules\TwigRender
    formatter:
        class: \Backend\Core\Utilities\Formatter
        factory_class: \Backend\Core\Utilities\Formatter
        factory_method: factory
        arguments:
            - @service_container
    backend.base.formats.html:
        class: \Backend\Base\Formats\Html
        arguments:
            - @request
            - @application.config
            - @renderer
    session:
        class: \Backend\Modules\Storage\NativeSession

# Set application settings here
application:
    values:
        applicationName: "Backend PHP"