# Reference all services likely to be used in the application here
parameters:
    backend.router.config_file: routes

services:
    backend.router.config:
        class: \Backend\Core\Utilities\Config
        factory_class: \Backend\Core\Utilities\Config
        factory_method: getNamed
        arguments:
            - @backend.parser
            - %backend.router.config_file%
    backend.parser:
        class: \Symfony\Component\Yaml\Parser
    backend.callback_factory:
        class: \Backend\Core\Utilities\CallbackFactory
    backend.router:
        class: \Backend\Core\Utilities\Router
        arguments:
            - @backend.router.config
            - @backend.callback_factory
    backend.renderer:
        class: \Backend\Modules\TwigRender
    backend.base.formats.html:
        class: \Backend\Base\Formats\Html
        arguments:
            - @backend.request
            - @backend.application.config
            - @backend.renderer

# Set application settings here
application:
    values:
        applicationName: "Backend PHP"

# Set DB Connections here
database:
    default:
        connection:
            driver: sqlite
            path: /tmp/backend-core.sqlite

    default_mysql:
        connection:
            driver: mysql
            username: username
            password: password
            host: localhost
            dbname: database
