# Reference all services likely to be used in the application here
parameters:
    Router.ConfigFile: routes

services:
    RouterConfig:
        class: \Backend\Core\Utilities\Config
        factory_class: \Backend\Core\Utilities\Config
        factory_method: getNamed
        arguments: [ %Router.ConfigFile% ]
    Backend\Interfaces\CallbackFactoryInterface:
        class: \Backend\Core\Utilities\CallbackFactory
    Backend\Interfaces\RouterInterface:
        class: \Backend\Core\Utilities\Router
        arguments:
            - @RouterConfig
            - @Backend\Interfaces\CallbackFactoryInterface

# Set application settings here
application:
    values:
        applicationName: "Backend PHP"

# Set DB Connections here
database:
    default:
        connection:
            driver: sqlite
            path: /tmp/backend-core.sqlite

    default_mysql:
        connection:
            driver: mysql
            username: username
            password: password
            host: localhost
            dbname: database
