# Reference all tools likely to be used in the application here
tools:
#    Render: Backend\Base\Utilities\Render
    Render: Backend\Base\Utilities\TwigRender
#    Logger: Backend\Core\Utilities\Logger
    Logger: Backend\Core\Utilities\PearLogger
    PearLogger:
        - Backend\Base\Utilities\PearLogger
        -
            filename: '/tmp/backend-pear.log'

# Add observers to subject classes here. The observers should refer to the tool name
subjects:
    Backend\Core\Application:
        observers:
            - Logger
            - PearLogger
    Backend\Core\Utilities\ApplicationEvent:
        observers:
            - Logger
            - PearLogger

# Set application settings here
application:
    values:
        applicationName: "Backend PHP"

# Set DB Connections here
database:
    default:
        connection:
            driver: sqlite
            path: /tmp/backend-core.sqlite

    default_mysql:
        connection:
            driver: mysql
            username: username
            password: password
            host: localhost
            dbname: database
