# Reference all services likely to be used in the application here
services:
    backend.Render: Backend\Base\Utilities\Render
    backend.Logger: Backend\Core\Utilities\Logger
    backend.PearLogger:
        - Backend\Core\Utilities\PearLogger
        -
            -
                filename: '/tmp/backend-pear.log'

# Add observers to subject classes here. The observers should refer to the tool name
subjects:
    Backend\Core\Application:
        observers:
            - backend.Logger
            - backend.PearLogger
    Backend\Core\Utilities\ApplicationEvent:
        observers:
            - backend.Logger
            - backend.PearLogger

# Set application settings here
application:
    values:
        applicationName: "Backend PHP"

# Set DB Connections here
database:
    default:
        connection:
            driver: sqlite
            path: /tmp/backend-core.sqlite

    default_mysql:
        connection:
            driver: mysql
            username: username
            password: password
            host: localhost
            dbname: database
