# Reference all services likely to be used in the application here
services:
    backend.Render: Backend\Modules\Render

# Set application settings here
application:
    values:
        applicationName: "Backend PHP"

# Set DB Connections here
database:
    default:
        connection:
            driver: sqlite
            path: /tmp/backend-core.sqlite

    default_mysql:
        connection:
            driver: mysql
            username: username
            password: password
            host: localhost
            dbname: database
