# Define all custom routes here
routes:
    home:
        route: /
        callback: \Backend\Base\Controllers\ExamplesController::home

    test:
        route: /this/is/<id>/<another>
        callback: \Backend\Base\Controllers\ExamplesController::params
        defaults:
            another: 'string'

    verb:
        verb: post
        route: /
        callback: \Backend\Base\Controllers\ExamplesController::post

# Map the area part of the url to a controller
controllers:
    something: \Backend\Base\Controllers\ExamplesController
