# Define all custom routes here
routes:
    home:
        route: /
        callback: \Backend\Base\Controllers\ExamplesController::home

    test:
        route: /this/is/<id>/<another>
        callback: \Backend\Base\Controllers\ExamplesController::params
        defaults:
            another: 'string'
    verb:
        verb: post
        route: /
        callback: \Backend\Base\Controllers\ExamplesController::post
    value_form:
        verb: get
        route: /value/form
        callback: \Backend\Base\Controllers\ValuesController::form

# Map the area part of the url to a controller
controllers:
    example: \Backend\Base\Controllers\ExamplesController
    value: \Backend\Base\Controllers\ValuesController
